const dungeon = {};
dungeon.floors = [{
    name: "Crypt",
    theme: "undead",
    possibleEnemies: [enemies.Mouse],
    enemyProbabilities: [1],
    wavesRequiredToPass: 10,
    waveLevelValueMin: 2,
    waveLevelValueMax: 3,
}, {
    name: "",
    theme: "undead",
    possibleEnemies: [enemies.Rat],
    enemyProbabilities: [1],
    wavesRequiredToPass: 10,
    waveLevelValueMin: 2,
    waveLevelValueMax: 3,
}, {
    name: "",
    theme: "undead",
    possibleEnemies: [enemies.Slime],
    enemyProbabilities: [1],
    wavesRequiredToPass: 10,
    waveLevelValueMin: 2,
    waveLevelValueMax: 3,
}, {
    name: "",
    theme: "undead",
    possibleEnemies: [enemies.Slime, enemies.Rat],
    enemyProbabilities: [3,1],
    wavesRequiredToPass: 10,
    waveLevelValueMin: 2,
    waveLevelValueMax: 3,
}, {
    name: "",
    theme: "undead",
    possibleEnemies: [enemies.Mouse,enemies.Rat],
    enemyProbabilities: [1,1],
    wavesRequiredToPass: 1,
    waveLevelValueMin: 2,
    waveLevelValueMax: 3,
}, {
    name: "Caves",
    theme: "caves",
    possibleEnemies: [enemies.Mouse, enemies.Rat, enemies.Slime],
    enemyProbabilities: [1, 2, 1],
    wavesRequiredToPass: 1,
    waveLevelValueMin: 2,
    waveLevelValueMax: 3,
}, {
    name: "",
    theme: "caves",
    possibleEnemies: [enemies.Mouse, enemies.Rat],
    enemyProbabilities: [90, 1],
    wavesRequiredToPass: 1,
    waveLevelValueMin: 2,
    waveLevelValueMax: 3,
}, {
    name: "",
    theme: "caves",
    possibleEnemies: [enemies.Mouse],
    enemyProbabilities: [1],
    wavesRequiredToPass: 10,
    waveLevelValueMin: 2,
    waveLevelValueMax: 3,
}, {
    name: "",
    theme: "caves",
    possibleEnemies: [enemies.Mouse],
    enemyProbabilities: [1],
    wavesRequiredToPass: 1,
    waveLevelValueMin: 2,
    waveLevelValueMax: 3,
}, {
    name: "",
    theme: "caves",
    possibleEnemies: [enemies.Mouse],
    enemyProbabilities: [1],
    wavesRequiredToPass: 1,
    waveLevelValueMin: 2,
    waveLevelValueMax: 3,
}];